### ISSUE TITLE
RowAction without Text

### ISSUE THREAD

**Issue by cakl** [benguild/BGTableViewRowActionWithImage#10]
Feature Request: Just showing an image without underlying text.

**Comment by benguild** [comment]
Hmm, it could be done.
Do you want to add it? Feel free to submit a PR.

**Comment by cakl** [comment]
My problem is that I don't know how to generate an empty/invisible string with a certain width (the image width). Think thats needed to generate the UITableRowAction. Any ideas?

**Comment by benguild** [comment]
Hmm, I see what you mean. Have you tried using the "fitted width" methods that @klauslanza contributed? I would think you could just put `nil` or a blank string for the text, but I'm not sure about the vertical alignment of the image as I don't think the current version of the pod/library handles that case.

Perhaps the methods could be modified to not add a vertical offset/padding for the image if a `nil` string is passed.

**Comment by benguild** [comment]
Sorted out by #14.
