### ISSUE TITLE
Some vertical alignment issues with taller cells.

### ISSUE THREAD

**Issue by benguild** [benguild/BGTableViewRowActionWithImage#12]
Can adjust images manually, but it'd be better to refactor this.

**Comment by benguild** [comment]
Somewhat fixed by #14 when not using text.

**Comment by bestwnh** [comment]
Is this what you want? https://github.com/benguild/BGTableViewRowActionWithImage/pull/17

**Comment by benguild** [comment]
Hmm, I don't think this issue is related, but I think ultimately the issue might be related to the size of the icon/image used. Either way, I'll close this out as I'll merge your PR.
