### ISSUE TITLE
RowAction highlighted.

### ISSUE THREAD

**Issue by waydevin** [benguild/BGTableViewRowActionWithImage#15]
Thanks for this awesome library!

Is it possible to highlight the row action only when it's tapped?
More like highlight it at the state similar to `.touchDownInside` for an `UIButton`.

**Comment by benguild** [comment]
I don't believe what you want to do here is possible using the Apple-provided stuff in `UIKit`. However, you might want to search around and see if anyone else's custom implementations of functionality like this do what you like.
