### ISSUE TITLE
Wrong width on ios11

### ISSUE THREAD

**Issue by antonioreyna** [benguild/BGTableViewRowActionWithImage#21]
Hello now the width is smaller than the button so the image and text cuts off

**Comment by benguild** [comment]
Hi, this library is actually *not* supported anymore in iOS 11. You should use `UIContextualAction`. — If you're interested in updating the code to use this automatically for iOS 11+, please submit a pull-request with your changes.

FYI, you're probably seeing stuff in the log/console warning you about this.

**Comment by antonioreyna** [comment]
[TableView] Setting a pattern color as backgroundColor of UITableViewRowAction is no longer supported.
