### ISSUE TITLE
How to use this library with row height = AutomaticDmension

### ISSUE THREAD

**Issue by hoangminhgreen** [benguild/BGTableViewRowActionWithImage#24]
Hey guys, I have a trouble. My tableview set rowheight = UITableviewAutomaticDimension, so I can not get row height value (height = -1).
Therefore, I can init a JATableViewRowAction with a true heigh. 
Pls help me, what should I do???

**Comment by benguild** [comment]
You could get the cell and check its actual height, maybe?

```obj-c
[[tableView cellForRowAtIndexPath:indexPath] frame].size.height
```
