### ISSUE TITLE
When device language Direction is RightToLeft buttons comes empty 

### ISSUE THREAD

**Issue by bamohammad** [benguild/BGTableViewRowActionWithImage#25]
When device language Arabic and use image and title it shows to me empty 
<img width="289" alt="screen shot 2018-08-01 at 1 14 17 pm" src="https://user-images.githubusercontent.com/19460934/43516007-d6459e02-958c-11e8-828b-6431855aaa55.png">

**Comment by benguild** [comment]
This library has been deprecated.
