### ISSUE TITLE
Swipe cells different width.

### ISSUE THREAD

**Issue by klauslanza** [benguild/BGTableViewRowActionWithImage#6]
Cells with different labels length gets different width.
Should be possible to choose a width to keep it uniform.

As a solution for now: just pad the shortest label with right/left spaces to reach the longest one size :-)

![same_size](https://cloud.githubusercontent.com/assets/1684798/15006403/d71554a4-11d0-11e6-8929-be4d9249e32c.png)
![differnet_size](https://cloud.githubusercontent.com/assets/1684798/15006404/d8193956-11d0-11e6-9e1d-ed60403a332d.png)

**Comment by benguild** [comment]
What would happen when the text is too long?You're welcome to submit a PR with a proposed option to make them all the same length with ellipsis... but it definitely shouldn't clip. 

```
_____________________________
```
