### ISSUE TITLE
Swift Compatibility?

### ISSUE THREAD

**Issue by kit24** [benguild/BGTableViewRowActionWithImage#9]

**Comment by benguild** [comment]
I don't know, I've never personally used it in a Swift project. However, there's nothing about it that shouldn't work as far as I know. If you want to update the documentation feel free.

**Comment by benguild** [comment]
Or, post examples and I'll update the documentation.

**Comment by kit24** [comment]
I am pretty new to this myself. Any idea how I would use your library to write a UITableViewRowAction in a swift class?

**Comment by benguild** [comment]
Try importing the library once you've added it as a Pod:

```
import BGTableViewRowActionWithImage
```

Then, start typing this into Xcode and see if it prompts you for the initializer properties:

```
BGTableViewRowActionWithImage()
```

**Comment by kit24** [comment]
This is the only option I get BGTableViewRowActionWithImage(style: <UITableViewRowActionStyle>, title: <String?>, handler: <(UITableViewRowAction, NSIndexPath) -> Void>)
Don't have an option to add image here.

**Comment by benguild** [comment]
Hmm, weird. Unfortunately I don't have time to look into it right now... since as mentioned I haven't used it in a Swift project. But, if you figure out what is wrong let me know and I'll things as necessary later on.

**Comment by kit24** [comment]
So the problem was that the other constructors were not in fact init() methods but public class functions, That's why they didn't show up in a straightforward manner. Have to call them as BGTableViewRowActionWithImage.rowActionWithStyle(....

**Comment by benguild** [comment]
Oh, yeah I'm surprised that didn't pop up when you started typing what I wrote above. Can you post some sample calls formatted in Swift (like the `README`) indicates and I'll update the docs and close this issue?

**Comment by kit24** [comment]
This is an example of using your methods in swift. Everything in < > has to be replaced by actual values:
 `let tableViewRowAction = BGTableViewRowActionWithImage.rowActionWithStyle(
<UITableViewRowActionStyle>, title: <String!>, titleColor: <UIColor!>, backgroundColor: <UIColor!>, image: <UIImage!>, forCellHeight: <UInt>, andFittedWidth: <Bool>, handler: <((UITableViewRowAction!, NSIndexPath!) -> Void)! ((UITableViewRowAction!, NSIndexPath!) -> Void)! (UITableViewRowAction!, NSIndexPath!) -> Void>)`
